/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#005235",
        "background": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#27313f",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00174d",
        "surface": "#f8f9ff",
        "surface-container-high": "#dee9fc",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#737686",
        "primary": "#003fb1",
        "on-surface-variant": "#434654",
        "tertiary": "#005538",
        "surface-dim": "#d0dbed",
        "on-surface": "#121c2a",
        "on-tertiary-fixed": "#002113",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1a56db",
        "surface-tint": "#1353d8",
        "surface-variant": "#d9e3f6",
        "on-secondary-fixed-variant": "#93000c",
        "tertiary-fixed-dim": "#71daa8",
        "on-tertiary-container": "#89f2be",
        "on-secondary-container": "#fffbff",
        "on-primary-container": "#d4dcff",
        "on-primary-fixed-variant": "#003dab",
        "secondary-container": "#de2d2b",
        "secondary-fixed-dim": "#ffb4ab",
        "on-error": "#ffffff",
        "tertiary-fixed": "#8ef7c2",
        "surface-container-highest": "#d9e3f6",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b5c4ff",
        "on-secondary-fixed": "#410002",
        "secondary-fixed": "#ffdad6",
        "on-background": "#121c2a",
        "inverse-primary": "#b5c4ff",
        "surface-bright": "#f8f9ff",
        "secondary": "#ba0915",
        "surface-container": "#e6eeff",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c5d7",
        "tertiary-container": "#00704b",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
